
                             <div class="form-group">
                                <label class="col-md-4 control-label" for="crear"></label>
                                <div class="col-md-8">
                                    <button id="crear" name="crear" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>
                                    <?php echo Html::link(Router::get('module').Router::get('controller').'/', '<i class="fa fa-times"></i> Cancelar', 'class="btn btn-danger"'); ?>
                                </div>
                            </div>