

        <footer class="navbar-inverse navbar-fixed-bottom">
            <div class="container">
                <p>
                    Desarrollado por <a href="http://www.icter.us">Icterus, C.A.</a>
                    <span class="pull-right">Versión: <?php echo APP_VERSION ?> - IP: <?php echo Utils::getIp(); ?> - Tiempo: <?php echo round((microtime(1)-START_TIME),4); ?> seg</span>
                </p>
            </div>
        </footer>

