
                <?php View::partial('botonera', 604800, array('buscar'=>True)); ?>

                <?php View::content(); ?>

                <form class="form-horizontal" id="buscador">
                <fieldset>

                <legend>Buscar</legend>

                <div class="form-group">
                  <label class="col-md-4 control-label" for="matricula">Matrícula</label>

                  <div class="col-md-2">
                        <?php echo Form::text('avion.matricula', 'class="form-control mask-alphanum" placeholder="Matrícula" required="required"') ?>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-md-4 control-label" for="singlebutton"></label>
                  <div class="col-md-2">
                    <button id="buscando" type="submit" class="btn btn-primary">
                        <i class="fa fa-search"></i> Buscar
                    </button>
                  </div>
                  <div class="col-md-2">
                    <button id="reset" class="btn btn-danger">
                        <i class="fa fa-times"></i> Cancelar
                    </button>
                  </div>
                </div>

                </fieldset>
                </form> <!-- Buscador -->

                <p>&nbsp;</p>
                <table class="table table-striped table-condensed grid">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Marca</th>
                            <th>Modelo</th>
                            <th>Matrícula</th>

                            <th class="text-center">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Datos Cargados de manera asincrona -->
                    </tbody>
                </table>
                <script id="items" type="text/x-jquery-tmpl">
                        <tr>
                            <td>${id}</td>
                            <td>${marca}</td>
                            <td>${modelo}</td>
                            <td>${matricula}</td>
                            <td class="text-center">
                                <?php echo Html::link(Router::get('controller').'/modificar/${id}', '<i class="fa fa-edit"></i> Editar', 'class="btn btn-primary" title="Modificar"'); ?>
                                <?php echo Html::link(Router::get('controller').'/borrar/${id}/', '<i class="fa fa-trash-o"></i> Borrar', 'class="btn btn-danger" title="Borrar"'); ?>
                            </td>
                        </tr>
                </script>
                <?php echo Tag::js('utils'); ?>
                <?php Utils::paginacion(Router::get('controller').'/', True, True, 6); ?>
