
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <?php echo Form::open(null, 'post', 'class="form-horizontal"'); ?>
                        <fieldset>
                            <legend><?php echo ucfirst(Router::get('action')); ?></legend>
                            <?php View::content(); ?>

                            <h4>Procedencia</h4>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="modelo_marca">País :</label>
                                <div class="col-md-4">
                                    <?php echo TwForm::cmbPaises('ruta.pais', 'class="form-control" required="required"'); ?>
                                </div>
                            </div>


                            <div class="form-group">
                                <label class="col-md-4 control-label" for="modelo_ubicacion">Código IATA :</label>
                                <div id="aeropuerto" class="col-md-2">
                                  <?php echo Form::text('ruta.codigo', 'class="form-control upper" required="required" maxlength="4"'); ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="modelo_ubicacion">Nombre Aeropuerto:</label>
                                <div id="aeropuerto" class="col-md-5">
                                  <?php echo Form::text('ruta.aeropuerto', 'class="form-control upper" required="required"'); ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-4 control-label" for="crear"></label>
                                <div class="col-md-8">
                                    <button id="crear" name="crear" class="btn btn-success">
                                        <i class="fa fa-check"></i> Guardar
                                    </button>
                                </div>
                            </div>

                        </fieldset>
                    </form>
                </div>
            </div>
            <script type="text/javascript" src="/iaef/sistema/javascript/utils.js"></script>