
                <?php View::partial('botonera', 604800, array('buscar'=>True)); ?>

                <?php View::content(); ?>

                <form class="form-horizontal" id="buscador">
                <fieldset>

                <legend>Buscar</legend>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="avion_aerolinea_id">Aerolinea</label>
                    <div class="col-md-4">
                        <?php //echo Form::dbSelect('destino_procedencia.id', 'aerolinea', NULL, 'Seleccione', 'class="form-control"'); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="avion_marca_id">Procedencia</label>
                    <div class="col-md-4">
                        <?php echo Form::text('rutas.procedencia', 'placeholder="Procedencia" class="form-control"'); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="modelo">Destino</label>
                    <div class="col-md-4">
                        <?php echo Form::text('rutas.destino', 'placeholder="Destino" class="form-control"'); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label" for="singlebutton"></label>
                    <div class="col-md-2">
                        <button id="buscando" type="submit" class="btn btn-primary">
                            <i class="fa fa-search"></i> Buscar
                        </button>
                    </div>
                    <div class="col-md-2">
                        <button id="reset" class="btn btn-danger">
                            <i class="fa fa-times"></i> Cancelar
                        </button>
                    </div>
                </div>

                </fieldset>
                </form> <!-- Buscador -->

                <p>&nbsp;</p>
                <div id="datos">
                <table class="table table-striped table-condensed grid">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th class="celda-principal">Procedencia</th>
                            <th class="celda-principal">Destino</th>
                            <th class="text-center">Tipo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Datos Cargados de manera asincrona -->
                    </tbody>
                </table>
                <script id="items" type="text/x-jquery-tmpl">
                        <tr>
                            <td>${id}</td>
                            <td>${procedencia}</td>
                            <td>${destino}</td>
                            <td class="text-center">
                            {{if tipo == 'I'}}
                                <span class="label label-info">Internacional</span>
                            {{else}}
                                <span class="label label-success">Nacional</span>
                            {{/if}}
                            </td>
                        </tr>
                </script>
                <?php echo Tag::js('utils'); ?>
                <?php Utils::paginacion(Router::get('controller').'/', True, True, 6); ?>
                </div>
            </div>
