
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">

                    <?php echo Form::open(null, 'post', 'class="form-horizontal"'); ?>
                        <fieldset>
                            <legend><?php echo ucfirst(Router::get('action')),' ',ucfirst(Router::get('controller')); ?></legend>
                            <?php View::content(); ?>


                            <div class="form-group"> 
                                     <label class="col-md-4 control-label" for="descripcion">Descripcion</label>  
                                 <div class="col-md-5">
                                    <?php echo Form::hidden('servicio.id'); ?>
                                    <?php echo Form::text('servicio.servicio', 'class="form-control input-md mask-text" placeholder="Descripcion del servicio" required') ?>
                               </div>   
                            </div> 

                            <div class="form-group">
                              <label class="col-md-4 control-label" for="valor">Valor</label>
                              <div class="col-md-3">
                                <div class="input-group">
                                    <?php echo Form::text('servicio.valor', 'class="form-control mask-money" placeholder="Valor" required="required" maxlength="6"') ?>
                                  <span class="input-group-addon">BsF.</span>
                                </div>
                              </div>
                            </div>

                            <?php echo Form::hidden('servicio.estatus', NULL, 1) ?>
        <!-- Boton de Envio de Formulario -->

                          <?php View::partial('botoneranuevo'); ?>
          
                        </fieldset>

<?php echo Form::close() ?>

                </div>
            </div>
        </div>
        <?php echo Tag::js('jquery.keyfilter'); ?>
        <?php echo Tag::js('utils'); ?>