<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="<?php echo APP_CHARSET ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes">

        <title><?php echo $title; ?></title>

        <?php Tag::css('bootstrap.min'); // Bootstrap 3.1.0 ?>
        <?php Tag::css('font-awesome.min'); // Font Awesome 4.0.3 ?>
        <?php Tag::css('bootstrap-theme'); ?>
        <?php echo Html::includeCss() ?>

        <?php echo Tag::js('jquery.min'); // jQuery 1.10.2?>
        <?php echo Tag::js('bootstrap.min'); ?>

        <!--Load the AJAX API-->
        <!-- <script type="text/javascript" src="https://www.google.com/jsapi" async></script> -->

    </head>
    <body>

        <?php View::partial('nav'); ?>

        <div class="container">
            <div class="row">
                <?php View::content(); ?>
            </div>
        </div>

        <?php View::partial('footer'); ?>

</body>
</html>
